# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 85..100
  round: down
  precision: 1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%

ignore:
  - "tests" # Test files aren't important for coverage
  - "crates/testing" # Testing crate contains Test helpers which aren't important for coverage
  - "crates/cli" # CLI crate contains prompts to the user, which we currently deem not important for coverage

# Make comments less noisy
comment:
  layout: "files"
  require_changes: true
