[advisories]
ignore = [
  # FIXME!: See https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643.
  # There is no workaround available yet.
  "RUSTSEC-2023-0071",
  # FIXME: backoff => used in backend, need to be replaced with backon
  "RUSTSEC-2024-0384",
  # FIXME: derivative => used for default impls
  "RUSTSEC-2024-0388",
]
